services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: unless-stopped
